" special cursor logic
noremap [a<SPACE> 1k
noremap [s<SPACE> 2k
noremap [d<SPACE> 3k
noremap [f<SPACE> 4k
noremap [g<SPACE> 5k
noremap [h<SPACE> 6k
noremap [j<SPACE> 7k
noremap [k<SPACE> 8k
noremap [l<SPACE> 9k
noremap [a;<SPACE> 10k
noremap [aa<SPACE> 11k
noremap [as<SPACE> 12k
noremap [ad<SPACE> 13k
noremap [af<SPACE> 14k
noremap [ag<SPACE> 15k
noremap [ah<SPACE> 16k
noremap [aj<SPACE> 17k
noremap [ak<SPACE> 18k
noremap [al<SPACE> 19k
noremap [s;<SPACE> 20k
noremap [sa<SPACE> 21k
noremap [ss<SPACE> 22k
noremap [sd<SPACE> 23k
noremap [sf<SPACE> 24k
noremap [sg<SPACE> 25k
noremap [sh<SPACE> 26k
noremap [sj<SPACE> 27k
noremap [sk<SPACE> 28k
noremap [sl<SPACE> 29k
noremap [d;<SPACE> 30k
noremap [da<SPACE> 31k
noremap [ds<SPACE> 32k
noremap [dd<SPACE> 33k
noremap [df<SPACE> 34k
noremap [dg<SPACE> 35k
noremap [dh<SPACE> 36k
noremap [dj<SPACE> 37k
noremap [dk<SPACE> 38k
noremap [dl<SPACE> 39k
noremap [f;<SPACE> 40k
noremap [fa<SPACE> 41k
noremap [fs<SPACE> 42k
noremap [fd<SPACE> 43k
noremap [ff<SPACE> 44k
noremap [fg<SPACE> 45k
noremap [fh<SPACE> 46k
noremap [fj<SPACE> 47k
noremap [fk<SPACE> 48k
noremap [fl<SPACE> 49k
noremap [g;<SPACE> 50k
noremap [ga<SPACE> 51k
noremap [gs<SPACE> 52k
noremap [gd<SPACE> 53k
noremap [gf<SPACE> 54k
noremap [gg<SPACE> 55k
noremap [gh<SPACE> 56k
noremap [gj<SPACE> 57k
noremap [gk<SPACE> 58k
noremap [gl<SPACE> 59k
noremap [h;<SPACE> 60k
noremap [ha<SPACE> 61k
noremap [hs<SPACE> 62k
noremap [hd<SPACE> 63k
noremap [hf<SPACE> 64k
noremap [hg<SPACE> 65k
noremap [hh<SPACE> 66k
noremap [hj<SPACE> 67k
noremap [hk<SPACE> 68k
noremap [hl<SPACE> 69k
noremap [j;<SPACE> 70k
noremap [ja<SPACE> 71k
noremap [js<SPACE> 72k
noremap [jd<SPACE> 73k
noremap [jf<SPACE> 74k
noremap [jg<SPACE> 75k
noremap [jh<SPACE> 76k
noremap [jj<SPACE> 77k
noremap [jk<SPACE> 78k
noremap [jl<SPACE> 79k
noremap [k;<SPACE> 80k
noremap [ka<SPACE> 81k
noremap [ks<SPACE> 82k
noremap [kd<SPACE> 83k
noremap [kf<SPACE> 84k
noremap [kg<SPACE> 85k
noremap [kh<SPACE> 86k
noremap [kj<SPACE> 87k
noremap [kk<SPACE> 88k
noremap [kl<SPACE> 89k
noremap [l;<SPACE> 90k
noremap [la<SPACE> 91k
noremap [ls<SPACE> 92k
noremap [ld<SPACE> 93k
noremap [lf<SPACE> 94k
noremap [lg<SPACE> 95k
noremap [lh<SPACE> 96k
noremap [lj<SPACE> 97k
noremap [lk<SPACE> 98k
noremap [ll<SPACE> 99k
noremap [a;;<SPACE> 100k


noremap 'a<SPACE> 1j
noremap 's<SPACE> 2j
noremap 'd<SPACE> 3j
noremap 'f<SPACE> 4j
noremap 'g<SPACE> 5j
noremap 'h<SPACE> 6j
noremap 'j<SPACE> 7j
noremap 'k<SPACE> 8j
noremap 'l<SPACE> 9j
noremap ';<SPACE> 10j
noremap 'aa<SPACE> 11j
noremap 'as<SPACE> 12j
noremap 'ad<SPACE> 13j
noremap 'af<SPACE> 14j
noremap 'ag<SPACE> 15j
noremap 'ah<SPACE> 16j
noremap 'aj<SPACE> 17j
noremap 'ak<SPACE> 18j
noremap 'al<SPACE> 19j
noremap 's;<SPACE> 20j
noremap 'sa<SPACE> 21j
noremap 'ss<SPACE> 22j
noremap 'sd<SPACE> 23j
noremap 'sf<SPACE> 24j
noremap 'sg<SPACE> 25j
noremap 'sh<SPACE> 26j
noremap 'sj<SPACE> 27j
noremap 'sk<SPACE> 28j
noremap 'sl<SPACE> 29j
noremap 'd;<SPACE> 30j
noremap 'da<SPACE> 31j
noremap 'ds<SPACE> 32j
noremap 'dd<SPACE> 33j
noremap 'df<SPACE> 34j
noremap 'dg<SPACE> 35j
noremap 'dh<SPACE> 36j
noremap 'dj<SPACE> 37j
noremap 'dk<SPACE> 38j
noremap 'dl<SPACE> 39j
noremap 'f;<SPACE> 40j
noremap 'fa<SPACE> 41j
noremap 'fs<SPACE> 42j
noremap 'fd<SPACE> 43j
noremap 'ff<SPACE> 44j
noremap 'fg<SPACE> 45j
noremap 'fh<SPACE> 46j
noremap 'fj<SPACE> 47j
noremap 'fk<SPACE> 48j
noremap 'fl<SPACE> 49j
noremap 'g;<SPACE> 50j
noremap 'ga<SPACE> 51j
noremap 'gs<SPACE> 52j
noremap 'gd<SPACE> 53j
noremap 'gf<SPACE> 54j
noremap 'gg<SPACE> 55j
noremap 'gh<SPACE> 56j
noremap 'gj<SPACE> 57j
noremap 'gk<SPACE> 58j
noremap 'gl<SPACE> 59j
noremap 'h;<SPACE> 60j
noremap 'ha<SPACE> 61j
noremap 'hs<SPACE> 62j
noremap 'hd<SPACE> 63j
noremap 'hf<SPACE> 64j
noremap 'hg<SPACE> 65j
noremap 'hh<SPACE> 66j
noremap 'hj<SPACE> 67j
noremap 'hk<SPACE> 68j
noremap 'hl<SPACE> 69j
noremap 'j;<SPACE> 70j
noremap 'ja<SPACE> 71j
noremap 'js<SPACE> 72j
noremap 'jd<SPACE> 73j
noremap 'jf<SPACE> 74j
noremap 'jg<SPACE> 75j
noremap 'jh<SPACE> 76j
noremap 'jj<SPACE> 77j
noremap 'jk<SPACE> 78j
noremap 'jl<SPACE> 79j
noremap 'k;<SPACE> 80j
noremap 'ka<SPACE> 81j
noremap 'ks<SPACE> 82j
noremap 'kd<SPACE> 83j
noremap 'kf<SPACE> 84j
noremap 'kg<SPACE> 85j
noremap 'kh<SPACE> 86j
noremap 'kj<SPACE> 87j
noremap 'kk<SPACE> 88j
noremap 'kl<SPACE> 89j
noremap 'l;<SPACE> 90j
noremap 'la<SPACE> 91j
noremap 'ls<SPACE> 92j
noremap 'ld<SPACE> 93j
noremap 'lf<SPACE> 94j
noremap 'lg<SPACE> 95j
noremap 'lh<SPACE> 96j
noremap 'lj<SPACE> 97j
noremap 'lk<SPACE> 98j
noremap 'll<SPACE> 99j
noremap 'a;;<SPACE> 100j

